### ISSUE TITLE
Nothing happens when exporting

### ISSUE THREAD

**Issue by iamdriz** [here-erhe/Design-Token-Exporter#11]
Just been trying this with a sketch file and when I click the export button as the last step nothing happens. Instead of showing the dialog to pick a location where to save the export JSON/YAML it just does nothing.

Added a video showing what happens when I click the button.

[Screen Recording 2021-03-23 at 16.44.53.mov.zip](https://github.com/here-erhe/Design-Token-Exporter/files/6191392/Screen.Recording.2021-03-23.at.16.44.53.mov.zip)

This is Sketch: `Version 71 (115005)` running on: `macOS Big Sur 11.2.3`

**Comment by iamdriz** [comment]
I looked around and found the `crash.log` and the following output if that helps:

```
[
  {
    "context" : {
      "document" : "<MSDocument: 0x7fa6fc73dac0>",
      "newSelection" : [
        "<MSOvalShape: 0x7fa6fc6b6460> color\/primary (A058C48F-3A47-4712-8EE7-23A7CC8E72E5)"
      ],
      "oldSelection" : [

      ]
    },
    "identifier" : "SelectionChanged",
    "type" : "action end"
  },
  {
    "context" : {
      "document" : "<MSDocument: 0x7fa6fc73dac0>",
      "newArtboard" : "<MSArtboardGroup: 0x7fa6fc7bad90> Tokens (F5C0D413-75E7-4F68-AF67-929AAF86D9A1)",
      "oldArtboard" : "<null>"
    },
    "identifier" : "ArtboardChanged",
    "type" : "action start"
  },
  {
    "context" : {
      "document" : "<MSDocument: 0x7fa6fc73dac0>",
      "newArtboard" : "<MSArtboardGroup: 0x7fa6fc7bad90> Tokens (F5C0D413-75E7-4F68-AF67-929AAF86D9A1)",
      "oldArtboard" : "<null>"
    },
    "identifier" : "ArtboardChanged",
    "type" : "action end"
  },
  {
    "context" : {
      "action" : "<MSRunPluginAction: 0x60000327ecc0>"
    },
    "identifier" : "RunPlugin",
    "type" : "action start"
  },
  {
    "identifier" : "fi.erhe.design-token-exporter\/tokens.colors",
    "type" : "plugin run end",
    "version" : "1.0.1"
  },
  {
    "context" : {
      "command" : "fi.erhe.design-token-exporter\/tokens.colors",
      "document" : "<MSDocument: 0x7fa6fc73dac0>",
      "selection" : [
        "<MSOvalShape: 0x7fa6fc6b6460> color\/primary (A058C48F-3A47-4712-8EE7-23A7CC8E72E5)"
      ]
    },
    "identifier" : "RunPluginCommand",
    "type" : "action start"
  },
  {
    "context" : {
      "action" : "<MSLogAction: 0x6000004063f0>",
      "command" : "<MSPluginCommand: 0x60000090ec80>",
      "level" : "error",
      "payload" : [
        "Error: An Obj-C exception occurred."
      ],
      "stringValue" : "Error: An Obj-C exception occurred.\n    at [native code] (\/)\n    at \/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79280\n    at \/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79568\n    at __skpm_run (\/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79860)\n    at __skpm_run[native code] (\/)\n  nativeException: -[NSNull _getCString:maxLength:encoding:]: unrecognized selector sent to instance 0x7fff8019c610"
    },
    "identifier" : "Log",
    "type" : "action start"
  },
  {
    "context" : {
      "action" : "<MSLogAction: 0x6000004063f0>",
      "command" : "<MSPluginCommand: 0x60000090ec80>",
      "level" : "error",
      "payload" : [
        "Error: An Obj-C exception occurred."
      ],
      "stringValue" : "Error: An Obj-C exception occurred.\n    at [native code] (\/)\n    at \/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79280\n    at \/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79568\n    at __skpm_run (\/Users\/cameron\/Library\/Application Support\/com.bohemiancoding.sketch3\/Plugins\/design-token-exporter.sketchplugin\/Contents\/Sketch\/__colorTokens.js:1:79860)\n    at __skpm_run[native code] (\/)\n  nativeException: -[NSNull _getCString:maxLength:encoding:]: unrecognized selector sent to instance 0x7fff8019c610"
    },
    "identifier" : "Log",
    "type" : "action end"
  },
  {
    "context" : {
      "command" : "fi.erhe.design-token-exporter\/tokens.colors",
      "document" : "<MSDocument: 0x7fa6fc73dac0>",
      "selection" : [
        "<MSOvalShape: 0x7fa6fc6b6460> color\/primary (A058C48F-3A47-4712-8EE7-23A7CC8E72E5)"
      ]
    },
    "identifier" : "RunPluginCommand",
    "type" : "action end"
  },
  {
    "identifier" : "fi.erhe.design-token-exporter\/tokens.colors",
    "type" : "plugin run end",
    "version" : "1.0.1"
  },
  {
    "context" : {
      "action" : "<MSRunPluginAction: 0x60000327ecc0>"
    },
    "identifier" : "RunPlugin",
    "type" : "action end"
  }
]
```

**Comment by gutdingwillweilehaben** [comment]
I have the same problem. 

Sketch version ```72.4```, Plugin version ```1.0.1```, OS ```macOS Big Sur 11.2.3```

@iamdriz Did you find a solution to export the tokens anyway?

**Comment by mdillgen** [comment]
+1

**Comment by MongooseDoom** [comment]
It looks like it has something to do with `setAllowedFileTypes`. I commented out these lines in exportTokens.js and I was able to save a token json file:

```
let fileTypes = NSArray.arrayWithArray([values[type].filetype, nil]);

savePanel.setAllowedFileTypes(fileTypes)
```

I'm on Sketch version `77` and `macOS Big Sur 11.6`

**Comment by here-erhe** [comment]
Project is not maintained anymore
